"""
Teste
DAG auto-generated by Astro Cloud IDE.
"""
from __future__ import annotations

from datetime import timedelta
import pendulum
from airflow.decorators import dag, task


@dag(
    dag_id="hello_astro",
    description="DAG mínima para teste no Airflow 3 (TaskFlow).",
    start_date=pendulum.datetime(2025, 1, 1, tz="America/Sao_Paulo"),
    schedule="@daily",          # rode manualmente ou deixe agendar diariamente
    catchup=False,              # não roda execuções antigas
    default_args={
        "retries": 1,
        "retry_delay": timedelta(minutes=1),
    },
    tags=["teste", "astro"],
)
def hello_astro():
    @task
    def say_hello() -> str:
        msg = "Olá do Airflow 3 com Astro Runtime 3.0-11 (Python 3.12)!"
        print(msg)
        return msg

    @task
    def process(msg: str) -> None:
        print(f"Processando a mensagem: {msg}")

    process(say_hello())


dag = hello_astro()

